### PR TITLE
Add LIC and PAL log support

### PR DESCRIPTION
**Pull request by SanjulaGanepola**

### CODE REVIEW

**Review by ThePrez — APPROVED** [review]

**Comment by thebeardedgeek** [comment]
Jesse,How are you getting access to the LIC and PAL log? What table is that information in?Sent from my iPhoneOn Dec 18, 2024, at 9:46 AM, Sanjula Ganepola ***@***.***> wrote:﻿
Merged #171 into main.

**Comment by SanjulaGanepola** [comment]
Hello @thebeardedgeek. Users will define a [STRWCH](https://www.ibm.com/docs/en/i/7.4?topic=program-starting-watch-session#rzahb_startwatch__title__2) command that will watch for these logs. When a watch event is triggered the MANZAN handler (just an ILE program) will put the event data into a table (`MANZANMSG`, `MANZANVLOG`, or `MANZANPAL`) which the Manzan distributor will read off of and then send to the appropriate user defined destinations.

**Comment by thebeardedgeek** [comment]
That’s great! Is there a way to get to this same data using SQL to see what it would look like? I have a few systems I would like to use this for. Sent from my iPhoneOn Dec 18, 2024, at 10:13 AM, Sanjula Ganepola ***@***.***> wrote:﻿
Hello @thebeardedgeek. Users will define a STRWCH command that will watch for these logs. When a watch event is triggered the MANZAN handler (just an ILE program) will put the event data into a table (MANZANMSG, MANZANVLOG, or MANZANPAL) which the Manzan distributor will read off of and then send to the appropriate user defined destinations.

**Comment by SanjulaGanepola** [comment]
As you can see here in the [architecture](https://theprez.github.io/Manzan/#/?id=architecture), we want to support having custom code to be able to query off the table. However, in giving this a try now, it looks like we have a restriction on Manzan where a destination must be specified for a data source which must be lifted in order to support this (glad you brought this up!). I will have a look at fixing this.

To still see what the data looks like in the meantime, instead of starting Manzan, you could just start a watch program manually and specify it to call the Manzan `HANDLER` program. This will add to the table but not remove any entries off the table as the Manzan distributor is not started. You can then query those tables I mentioned earlier. For reference, the tables which Manzan uses look like this: https://github.com/ThePrez/Manzan/tree/main/ile/install_tasks

As a side note since you are interested in these LIC and PAL logs, are you aware of any reproducible way to trigger new LIC or PAL log entries? I have been trying to find a way to test this feature in Manzan, but have not found an easy way to trigger new logs to test if they are properly added to the table and then sent to a destination.

**Pull request merged**
